services:
  backend:
    build: ./backend
    container_name: music-backend
    ports:
      - "3000:3000"
    volumes:
      - uploads:/usr/src/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=music_db
    restart: always

  db:
    image: postgres:latest
    container_name: music-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=music_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
  uploads:
